/* automatically generated by rust-bindgen */

#![allow(non_camel_case_types)]

use ffi::attach_options::*;

pub enum Struct_lxc_lock { }
pub enum Struct_lxc_conf { }
#[repr(C)]
#[derive(Copy)]
pub struct Struct_lxc_container {
    pub name: *mut ::libc::c_char,
    pub configfile: *mut ::libc::c_char,
    pub pidfile: *mut ::libc::c_char,
    pub slock: *mut Struct_lxc_lock,
    pub privlock: *mut Struct_lxc_lock,
    pub numthreads: ::libc::c_int,
    pub lxc_conf: *mut Struct_lxc_conf,
    pub error_string: *mut ::libc::c_char,
    pub error_num: ::libc::c_int,
    pub daemonize: u8,
    pub config_path: *mut ::libc::c_char,
    pub is_defined: ::std::option::Option<extern "C" fn(c:
                                                            *mut Struct_lxc_container)
                                              -> u8>,
    pub state: ::std::option::Option<extern "C" fn(c:
                                                       *mut Struct_lxc_container)
                                         -> *const ::libc::c_char>,
    pub is_running: ::std::option::Option<extern "C" fn(c:
                                                            *mut Struct_lxc_container)
                                              -> u8>,
    pub freeze: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container)
                                          -> u8>,
    pub unfreeze: ::std::option::Option<extern "C" fn(c:
                                                          *mut Struct_lxc_container)
                                            -> u8>,
    pub init_pid: ::std::option::Option<extern "C" fn(c:
                                                          *mut Struct_lxc_container)
                                            -> ::libc::pid_t>,
    pub load_config: ::std::option::Option<extern "C" fn(c:
                                                             *mut Struct_lxc_container,
                                                         alt_file:
                                                             *const ::libc::c_char)
                                               -> u8>,
    pub start: ::std::option::Option<extern "C" fn(c:
                                                       *mut Struct_lxc_container,
                                                   useinit: ::libc::c_int,
                                                   argv:
                                                       *const *const ::libc::c_char)
                                         -> u8>,
    pub startl: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container,
                                                    useinit:
                                                        ::libc::c_int, ...)
                                          -> u8>,
    pub stop: ::std::option::Option<extern "C" fn(c:
                                                      *mut Struct_lxc_container)
                                        -> u8>,
    pub want_daemonize: ::std::option::Option<extern "C" fn(c:
                                                                *mut Struct_lxc_container,
                                                            state: u8) -> u8>,
    pub want_close_all_fds: ::std::option::Option<extern "C" fn(c:
                                                                    *mut Struct_lxc_container,
                                                                state: u8)
                                                      -> u8>,
    pub config_file_name: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container)
                                                    -> *mut ::libc::c_char>,
    pub wait: ::std::option::Option<extern "C" fn(c:
                                                      *mut Struct_lxc_container,
                                                  state:
                                                      *const ::libc::c_char,
                                                  timeout: ::libc::c_int)
                                        -> u8>,
    pub set_config_item: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             key:
                                                                 *const ::libc::c_char,
                                                             value:
                                                                 *const ::libc::c_char)
                                                   -> u8>,
    pub destroy: ::std::option::Option<extern "C" fn(c:
                                                         *mut Struct_lxc_container)
                                           -> u8>,
    pub destroy_with_snapshots: ::std::option::Option<extern "C" fn(c:
                                                                        *mut Struct_lxc_container)
                                                          -> u8>,
    pub save_config: ::std::option::Option<extern "C" fn(c:
                                                             *mut Struct_lxc_container,
                                                         alt_file:
                                                             *const ::libc::c_char)
                                               -> u8>,
    pub create: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container,
                                                    t: *const ::libc::c_char,
                                                    bdevtype:
                                                        *const ::libc::c_char,
                                                    specs:
                                                        *mut Struct_bdev_specs,
                                                    flags: ::libc::c_int,
                                                    argv:
                                                        *const *mut ::libc::c_char)
                                          -> u8>,
    pub createl: ::std::option::Option<extern "C" fn(c:
                                                         *mut Struct_lxc_container,
                                                     t: *const ::libc::c_char,
                                                     bdevtype:
                                                         *const ::libc::c_char,
                                                     specs:
                                                         *mut Struct_bdev_specs,
                                                     flags:
                                                         ::libc::c_int, ...)
                                           -> u8>,
    pub rename: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container,
                                                    newname:
                                                        *const ::libc::c_char)
                                          -> u8>,
    pub reboot: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container)
                                          -> u8>,
    pub shutdown: ::std::option::Option<extern "C" fn(c:
                                                          *mut Struct_lxc_container,
                                                      timeout: ::libc::c_int)
                                            -> u8>,
    pub clear_config: ::std::option::Option<extern "C" fn(c:
                                                              *mut Struct_lxc_container)
                                                -> ()>,
    pub clear_config_item: ::std::option::Option<extern "C" fn(c:
                                                                   *mut Struct_lxc_container,
                                                               key:
                                                                   *const ::libc::c_char)
                                                     -> u8>,
    pub get_config_item: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             key:
                                                                 *const ::libc::c_char,
                                                             retv:
                                                                 *mut ::libc::c_char,
                                                             inlen:
                                                                 ::libc::c_int)
                                                   -> ::libc::c_int>,
    pub get_running_config_item: ::std::option::Option<extern "C" fn(c:
                                                                         *mut Struct_lxc_container,
                                                                     key:
                                                                         *const ::libc::c_char)
                                                           ->
                                                               *mut ::libc::c_char>,
    pub get_keys: ::std::option::Option<extern "C" fn(c:
                                                          *mut Struct_lxc_container,
                                                      key:
                                                          *const ::libc::c_char,
                                                      retv:
                                                          *mut ::libc::c_char,
                                                      inlen: ::libc::c_int)
                                            -> ::libc::c_int>,
    pub get_interfaces: ::std::option::Option<extern "C" fn(c:
                                                                *mut Struct_lxc_container)
                                                  ->
                                                      *mut *mut ::libc::c_char>,
    pub get_ips: ::std::option::Option<extern "C" fn(c:
                                                         *mut Struct_lxc_container,
                                                     interface:
                                                         *const ::libc::c_char,
                                                     family:
                                                         *const ::libc::c_char,
                                                     scope: ::libc::c_int)
                                           -> *mut *mut ::libc::c_char>,
    pub get_cgroup_item: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             subsys:
                                                                 *const ::libc::c_char,
                                                             retv:
                                                                 *mut ::libc::c_char,
                                                             inlen:
                                                                 ::libc::c_int)
                                                   -> ::libc::c_int>,
    pub set_cgroup_item: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             subsys:
                                                                 *const ::libc::c_char,
                                                             value:
                                                                 *const ::libc::c_char)
                                                   -> u8>,
    pub get_config_path: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container)
                                                   -> *const ::libc::c_char>,
    pub set_config_path: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             path:
                                                                 *const ::libc::c_char)
                                                   -> u8>,
    pub clone: ::std::option::Option<extern "C" fn(c:
                                                       *mut Struct_lxc_container,
                                                   newname:
                                                       *const ::libc::c_char,
                                                   lxcpath:
                                                       *const ::libc::c_char,
                                                   flags: ::libc::c_int,
                                                   bdevtype:
                                                       *const ::libc::c_char,
                                                   bdevdata:
                                                       *const ::libc::c_char,
                                                   newsize: ::libc::uint64_t,
                                                   hookargs:
                                                       *mut *mut ::libc::c_char)
                                         -> *mut Struct_lxc_container>,
    pub console_getfd: ::std::option::Option<extern "C" fn(c:
                                                               *mut Struct_lxc_container,
                                                           ttynum:
                                                               *mut ::libc::c_int,
                                                           masterfd:
                                                               *mut ::libc::c_int)
                                                 -> ::libc::c_int>,
    pub console: ::std::option::Option<extern "C" fn(c:
                                                         *mut Struct_lxc_container,
                                                     ttynum: ::libc::c_int,
                                                     stdinfd: ::libc::c_int,
                                                     stdoutfd: ::libc::c_int,
                                                     stderrfd: ::libc::c_int,
                                                     escape: ::libc::c_int)
                                           -> ::libc::c_int>,
    pub attach: ::std::option::Option<extern "C" fn(c:
                                                        *mut Struct_lxc_container,
                                                    exec_function:
                                                        lxc_attach_exec_t,
                                                    exec_payload:
                                                        *mut ::libc::c_void,
                                                    options:
                                                        *mut lxc_attach_options_t,
                                                    attached_process:
                                                        *mut ::libc::pid_t)
                                          -> ::libc::c_int>,
    pub attach_run_wait: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             options:
                                                                 *mut lxc_attach_options_t,
                                                             program:
                                                                 *const ::libc::c_char,
                                                             argv:
                                                                 *const *const ::libc::c_char)
                                                   -> ::libc::c_int>,
    pub attach_run_waitl: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container,
                                                              options:
                                                                  *mut lxc_attach_options_t,
                                                              program:
                                                                  *const ::libc::c_char,
                                                              arg:
                                                                  *const ::libc::c_char, ...)
                                                    -> ::libc::c_int>,
    pub snapshot: ::std::option::Option<extern "C" fn(c:
                                                          *mut Struct_lxc_container,
                                                      commentfile:
                                                          *const ::libc::c_char)
                                            -> ::libc::c_int>,
    pub snapshot_list: ::std::option::Option<extern "C" fn(c:
                                                               *mut Struct_lxc_container,
                                                           snapshots:
                                                               *mut *mut Struct_lxc_snapshot)
                                                 -> ::libc::c_int>,
    pub snapshot_restore: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container,
                                                              snapname:
                                                                  *const ::libc::c_char,
                                                              newname:
                                                                  *const ::libc::c_char)
                                                    -> u8>,
    pub snapshot_destroy: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container,
                                                              snapname:
                                                                  *const ::libc::c_char)
                                                    -> u8>,
    pub snapshot_destroy_all: ::std::option::Option<extern "C" fn(c:
                                                                      *mut Struct_lxc_container)
                                                        -> u8>,
    pub may_control: ::std::option::Option<extern "C" fn(c:
                                                             *mut Struct_lxc_container)
                                               -> u8>,
    pub add_device_node: ::std::option::Option<extern "C" fn(c:
                                                                 *mut Struct_lxc_container,
                                                             src_path:
                                                                 *const ::libc::c_char,
                                                             dest_path:
                                                                 *const ::libc::c_char)
                                                   -> u8>,
    pub remove_device_node: ::std::option::Option<extern "C" fn(c:
                                                                    *mut Struct_lxc_container,
                                                                src_path:
                                                                    *const ::libc::c_char,
                                                                dest_path:
                                                                    *const ::libc::c_char)
                                                      -> u8>,
    pub attach_interface: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container,
                                                              dev:
                                                                  *const ::libc::c_char,
                                                              dst_dev:
                                                                  *const ::libc::c_char)
                                                    -> u8>,
    pub detach_interface: ::std::option::Option<extern "C" fn(c:
                                                                  *mut Struct_lxc_container,
                                                              dev:
                                                                  *const ::libc::c_char,
                                                              dst_dev:
                                                                  *const ::libc::c_char)
                                                    -> u8>,
    pub checkpoint: ::std::option::Option<extern "C" fn(c:
                                                            *mut Struct_lxc_container,
                                                        directory:
                                                            *mut ::libc::c_char,
                                                        stop: u8, verbose: u8)
                                              -> u8>,
    pub restore: ::std::option::Option<extern "C" fn(c:
                                                         *mut Struct_lxc_container,
                                                     directory:
                                                         *mut ::libc::c_char,
                                                     verbose: u8) -> u8>,
}
impl ::std::clone::Clone for Struct_lxc_container {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_lxc_container {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_lxc_snapshot {
    pub name: *mut ::libc::c_char,
    pub comment_pathname: *mut ::libc::c_char,
    pub timestamp: *mut ::libc::c_char,
    pub lxcpath: *mut ::libc::c_char,
    pub free: ::std::option::Option<extern "C" fn(s: *mut Struct_lxc_snapshot)
                                        -> ()>,
}
impl ::std::clone::Clone for Struct_lxc_snapshot {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_lxc_snapshot {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_bdev_specs {
    pub fstype: *mut ::libc::c_char,
    pub fssize: ::libc::uint64_t,
    pub zfs: Struct_Unnamed1,
    pub lvm: Struct_Unnamed2,
    pub dir: *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_bdev_specs {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_bdev_specs {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed1 {
    pub zfsroot: *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_Unnamed1 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed2 {
    pub vg: *mut ::libc::c_char,
    pub lv: *mut ::libc::c_char,
    pub thinpool: *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_Unnamed2 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed2 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[link(name = "lxc")]
extern "C" {
    pub fn lxc_container_new(name: *const ::libc::c_char,
                             configpath: *const ::libc::c_char)
     -> *mut Struct_lxc_container;
    pub fn lxc_container_get(c: *mut Struct_lxc_container) -> ::libc::c_int;
    pub fn lxc_container_put(c: *mut Struct_lxc_container) -> ::libc::c_int;
    pub fn lxc_get_wait_states(states: *mut *const ::libc::c_char)
     -> ::libc::c_int;
    pub fn lxc_get_global_config_item(key: *const ::libc::c_char)
     -> *const ::libc::c_char;
    pub fn lxc_get_version() -> *const ::libc::c_char;
    pub fn list_defined_containers(lxcpath: *const ::libc::c_char,
                                   names: *mut *mut *mut ::libc::c_char,
                                   cret: *mut *mut *mut Struct_lxc_container)
     -> ::libc::c_int;
    pub fn list_active_containers(lxcpath: *const ::libc::c_char,
                                  names: *mut *mut *mut ::libc::c_char,
                                  cret: *mut *mut *mut Struct_lxc_container)
     -> ::libc::c_int;
    pub fn list_all_containers(lxcpath: *const ::libc::c_char,
                               names: *mut *mut *mut ::libc::c_char,
                               cret: *mut *mut *mut Struct_lxc_container)
     -> ::libc::c_int;
    pub fn lxc_log_close() -> ();
}
